# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.


# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9104a9313f3cf9feb0ce2ccda50df8f517f83cb04bb1e2aa0d3e703f0e62c6d00edd7f74f563afda2110d9c4d5d74c97d50d3510b985250417084a5538ba4903

test:
  secret_key_base: 79d4baab28e2ab8343c8b2aa0a13891c4972abda797e32c5a2b03693282fb8768f3754a2e831eb4849b45eac9edf599813b8703d0115df3c7cac246b8f74f339

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
